import connection from '../../core/database/connection.js';

export default class PontoRepository {
  static async atual(tenantId: number, userId: number) { const c = await connection.connect(); try { const r = await c.query("SELECT * FROM time_entries WHERE tenant_id=$1 AND user_id=$2 AND status='open' ORDER BY started_at DESC LIMIT 1", [tenantId, userId]); return r.rows[0] || null; } finally { c.release(); } }
  static async iniciar(tenantId: number, userId: number, startedAt: string) { const c = await connection.connect(); try { const r = await c.query("INSERT INTO time_entries (tenant_id,user_id,started_at,status) VALUES ($1,$2,$3,'open') RETURNING *", [tenantId, userId, startedAt]); return r.rows[0]; } finally { c.release(); } }
  static async encerrar(id: number, tenantId: number, userId: number, endedAt: string, notes?: string) { const c = await connection.connect(); try { const r = await c.query("UPDATE time_entries SET ended_at=$1,status='closed',notes=COALESCE($2,notes),updated_at=NOW() WHERE id=$3 AND tenant_id=$4 AND user_id=$5 AND status='open' RETURNING *", [endedAt, notes || null, id, tenantId, userId]); return r.rows[0] || null; } finally { c.release(); } }
  static async historico(tenantId: number, userId: number) { const c = await connection.connect(); try { const r = await c.query('SELECT * FROM time_entries WHERE tenant_id=$1 AND user_id=$2 ORDER BY started_at DESC LIMIT 100', [tenantId, userId]); return r.rows; } finally { c.release(); } }
  static async solicitar(tenantId: number, userId: number, data: any) { const c = await connection.connect(); try { const r = await c.query('INSERT INTO time_entry_adjustment_requests (tenant_id,time_entry_id,user_id,requested_started_at,requested_ended_at,reason) SELECT $1,id,$2,$3,$4,$5 FROM time_entries WHERE id=$6 AND tenant_id=$1 AND user_id=$2 RETURNING *', [tenantId, userId, data.started_at, data.ended_at || null, data.reason, data.time_entry_id]); return r.rows[0] || null; } finally { c.release(); } }
  static async gerenciar(tenantId: number, status?: string) { const c = await connection.connect(); try { const r = await c.query(`SELECT te.*, u.name AS user_name, u.username FROM time_entries te JOIN users u ON u.id=te.user_id WHERE te.tenant_id=$1 ORDER BY te.started_at DESC LIMIT 500`, [tenantId]); return r.rows; } finally { c.release(); } }
  static async ajustes(tenantId: number) { const c = await connection.connect(); try { const r = await c.query('SELECT r.*, u.name AS user_name FROM time_entry_adjustment_requests r JOIN users u ON u.id=r.user_id WHERE r.tenant_id=$1 ORDER BY r.created_at DESC', [tenantId]); return r.rows; } finally { c.release(); } }
  static async revisar(id: number, tenantId: number, reviewerId: number, status: string) { const c = await connection.connect(); try { await c.query('BEGIN'); const req = await c.query('UPDATE time_entry_adjustment_requests SET status=$1,reviewed_by=$2,reviewed_at=NOW(),updated_at=NOW() WHERE id=$3 AND tenant_id=$4 AND status=\'pending\' RETURNING *', [status, reviewerId, id, tenantId]); if (status === 'approved' && req.rows[0]) await c.query('UPDATE time_entries SET started_at=$1,ended_at=$2,updated_at=NOW() WHERE id=$3 AND tenant_id=$4', [req.rows[0].requested_started_at, req.rows[0].requested_ended_at, req.rows[0].time_entry_id, tenantId]); await c.query('COMMIT'); return req.rows[0] || null; } catch (e) { await c.query('ROLLBACK'); throw e; } finally { c.release(); } }
}
